# Generated by Django 5.0.6 on 2024-06-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeFusion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
